// 3rd Party Imports
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Link from "next/link";
// Local Imports
import BackgroundImage from "@/components/backgroundComponent";
import giveNGoLogo from "@/images/GiveNGoLogoSparkles.png";
import TeamworkLogo from "@/images/Teamwork-Logo.png";
import DonateLogo from "@/images/Donate-Logo.png";
import loadData from "@/backend/loadData";

export default function Home() {
    useEffect(() => {
        if (!localStorage.getItem("dummyData")) {
            loadData();
        }
    });

    return (
        <>
            <Head>
                <title>Home | GiveNGo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <BackgroundImage/>
                <div className="absolute w-screen">
                    {/* <button onClick={() => loadData()}> Load Data </button> */}
                    {/* Acts like a container that fills up the whole screen */}
                    <div className="flex justify-center mt-10 flex-wrap space-y-16 w-screen">
                        <div className="flex flex-row w-screen justify-center">
                            <div className="w-72 lg:w-96">
                                <div className="">
                                    <Image
                                        className="h-max"
                                        src={giveNGoLogo}
                                        alt="Logo"
                                        priority
                                    />
                                </div>
                            </div>
                        </div>
                        {/* Added a row with desired width inside the container so it is not stretching full width */}
                        <div className="flex flex-col gap-y-3 lg:w-4/6 lg:flex-row justify-around">
                            <div className="flex flex-col bg-[#313039] border-[#25242B] border-8 rounded-xl">
                                <div className="p-6">
                                    <Link href="/donatePage">
                                        <button className="">
                                            <Image
                                                className="w-48 mb-4 mx-6"
                                                src={DonateLogo}
                                                alt="Donator"
                                            />
                                            <span className="text-4xl text-white">Donator</span>
                                        </button>
                                    </Link>
                                </div>
                            </div>
                            <div className="flex flex-col bg-[#313039] border-[#25242B] border-8 rounded-xl p-6">
                                <Link href="/postedItemsPage">
                                    <button className="">
                                        <Image
                                            className="w-48 mb-4 mx-6"
                                            src={TeamworkLogo}
                                            alt="Collector"/>
                                        <span className="text-4xl text-white mt-2">Collector</span>
                                    </button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
